In [ ]:
Integrantes:
    Juan David Viveros Chavez
    Luis Enrique Gil Mayser
    Luciana Valera Aspetty

Configuración básica

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
Cargar el dataset

In [8]:
# Cargar el dataset
df = pd.read_csv('/kaggle/input/obesity-prediction/obesity_data.csv')
df.head()

,Age,Gender,Height,Weight,BMI,PhysicalActivityLevel,ObesityCategory
0,56,Male,173.575262,71.982051,23.891783,4,Normal weight
1,69,Male,164.127306,89.959256,33.395209,2,Obese
2,46,Female,168.072202,72.930629,25.817737,4,Overweight
3,32,Male,168.459633,84.886912,29.912247,3,Overweight
4,60,Male,183.568568,69.038945,20.487903,3,Normal weight

In [ ]:
Verificar si no hay datos nulos

In [15]:
print(df.isnull().sum())
print("------------------------------------------------------------")
print(df.describe())
print("------------------------------------------------------------")
df.info()

Age                      0
Gender                   0
Height                   0
Weight                   0
BMI                      0
PhysicalActivityLevel    0
ObesityCategory          0
dtype: int64
------------------------------------------------------------
               Age       Height       Weight          BMI  \
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     49.857000   170.052417    71.205769    24.888317
std      18.114267    10.309971    15.509849     6.193912
min      18.000000   136.115719    26.065730     8.470572
25%      35.000000   163.514205    61.129629    20.918068
50%      50.000000   169.801665    71.929072    24.698647
75%      66.000000   177.353596    81.133746    28.732132
max      79.000000   201.419670   118.907366    50.791898

       PhysicalActivityLevel
count            1000.000000
mean                2.534000
std                 1.116284
min                 1.000000
25%                 2.000000
50%                 3.000000
75%                 4.000000
max                 4.000000
------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    1000 non-null   int64
 1   Gender                 1000 non-null   object
 2   Height                 1000 non-null   float64
 3   Weight                 1000 non-null   float64
 4   BMI                    1000 non-null   float64
 5   PhysicalActivityLevel  1000 non-null   int64
 6   ObesityCategory        1000 non-null   object
dtypes: float64(3), int64(2), object(2)
memory usage: 54.8+ KB

In [ ]:
Reprocesar datos

In [21]:
df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})
df['PhysicalActivityLevel'] = df['PhysicalActivityLevel'].astype('category').cat.codes
df['ObesityCategory'] = df['ObesityCategory'].astype('category').cat.codes